# kv
path = "/root"
proc = 10

[integer]
key1 = +99
key2 = 42

[boolean]
True = true
False = false

[boolean_array]
key = [true, false, false, true]

[string_array]
key2 = ["apple", "pear", "banana"]

[string]
str1 = "hello"
str2 = "world"

# array
[[products]]
name = "Hammer"
sku = 738594937

[[products]]
name = "Nail"
sku = 284758393
color = "gray"

# deep
[[fruit]]
  name = "apple"

  [fruit.physical.tt]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "pear"

  [fruit.physical.tt]
    color = "yellow"
    shape = "round"

  [[fruit.variety]]
    name = "yellow delicious"

  [[fruit.variety]]
    name = "granny smith"


[test]

    [test.server.timeout]
    key1 = "str1"
    key2 = 123

    [test.server.name]
    key1 = "str1"
    key2 = 123

    [test.client.timeout]
    key1 = "str1"
    key2 = 123

    [test.client.name]
    key1 = "str1"
    key2 = 123
    float_val = 3.1415926


    [test.golang]
    name = "test1"
    timeout = "300ms"